project 'Pixel_City.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pixel_City' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'Pixel_CityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pixel_CityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
